services:
  mcp-server:
    build: .
    container_name: mcp_server
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"  
    volumes:
      - .:/app
    networks:
      - shared_network
networks:
  shared_network:
    external: true